"""Agentic Trainer pipeline — port of the user's `agentic-pipeline` pattern.

The TrainingAgent drives this in stages:

  1. **Oracle baseline** — sklearn LogisticRegression on flattened input.
     Defines the "must beat by 5 points" sanity gate.
  2. **Generate design.md** — Nemotron writes architecture + hyperparams +
     wall-clock estimate as Markdown. Trainer pauses for HITL approval.
  3. **Generate code** — Nemotron writes `model.py`, `train.py`, `eval.py`
     into `data/artifacts/<run_id>/code/`. Sklearn-based for fast iteration.
  4. **Smoke harness** — verify the generated code: py_compile, import,
     `build_model()` runs, param count reasonable. Emits structured
     `verify_report.json` with one `ERROR`-prefixed line per failed check.
  5. **Subprocess training** — run `code/train.py` with wall-clock cap.
     Captures stdout/stderr to `logs/`. Soft-success if best.pkl exists
     even after timeout.
  6. **Load + return** — read best.pkl + final metrics into TrainingResult.

When this pattern matures, it'll absorb the multi-session restart + stuck
detector from the user's `agentic-pipeline` project. For now it's
single-shot per stage.
"""
from __future__ import annotations

import json
import subprocess
import sys
import time
from pathlib import Path
from typing import Any

import numpy as np
from pydantic import BaseModel, ConfigDict, Field

from agents._llm_client import NemotronClient
from contracts.schemas import (
    DatasetProfile,
    Modality,
    PreparationReport,
    StrategySpec,
    TrainingEnvelope,
)
from tools import training_tools as tt


# ===========================================================================
# Stage 1: Oracle baseline
# ===========================================================================
def run_oracle(
    profile: DatasetProfile,
    prep: PreparationReport | None,
    run_dir: Path,
) -> dict[str, Any]:
    """sklearn.LogisticRegression on flattened input. Save `oracle.json`.

    The oracle plays the same role as GCC in the C-compiler project: a
    known-good baseline the generated model must beat by ≥5 points.
    """
    from sklearn.linear_model import LogisticRegression
    from sklearn.metrics import accuracy_score

    t0 = time.time()
    if profile.modality == Modality.IMAGE:
        prepared = (
            Path(prep.prepared_dataset_path)
            if (prep and prep.prepared_dataset_path) else None
        )
        if prepared and (prepared / "train").is_dir() and (prepared / "test").is_dir():
            X_train, y_train, _ = tt.load_image_folder(prepared / "train")
            X_test, y_test, _ = tt.load_image_folder(prepared / "test")
        else:
            from sklearn.model_selection import train_test_split
            X, y, _ = tt.load_image_folder(Path(profile.dataset_path))
            X_train, X_test, y_train, y_test = train_test_split(
                X, y, test_size=0.2, random_state=42, stratify=y,
            )
    else:
        target = profile.target_column or "target"
        prepared_dir = (
            Path(prep.prepared_dataset_path)
            if (prep and prep.prepared_dataset_path) else None
        )
        X_train, y_train, X_test, y_test = tt.load_csv_split_or_full(
            prepared_dir=prepared_dir,
            fallback_csv=Path(profile.dataset_path),
            target_column=target,
        )
        if X_test is None or y_test is None:
            from sklearn.model_selection import train_test_split
            X_train, X_test, y_train, y_test = train_test_split(
                X_train, y_train, test_size=0.2, random_state=42,
            )

    model = LogisticRegression(max_iter=300, n_jobs=-1)
    model.fit(X_train, y_train)
    acc = float(accuracy_score(y_test, model.predict(X_test)))
    wall = time.time() - t0

    oracle = {
        "model": "sklearn.linear_model.LogisticRegression",
        "test_accuracy": acc,
        "wall_clock_s": wall,
        "n_train": int(X_train.shape[0]),
        "n_test": int(X_test.shape[0]),
        "n_features": int(X_train.shape[1]) if X_train.ndim > 1 else 1,
    }
    (run_dir / "oracle.json").write_text(json.dumps(oracle, indent=2))
    return oracle


# ===========================================================================
# Stage 2 + 3 (combined): Generate design.md AND code in ONE call.
# Avoids: (a) two sequential ~3min Nemotron round-trips, (b) restating what
# Profiler/Researcher/Preparer already wrote — the model is explicitly told
# those upstream agents already own the architectural and dataset reasoning.
# ===========================================================================
class _DesignAndCode(BaseModel):
    """Structured output: design.md + model.py.

    train.py is NOT generated by the LLM — it's a templated runner owned by
    AutoForge. The LLM is bug-prone about data-loading (invents `np.load`
    paths, expects CSV when given images, etc.). Separating "creative
    architecture choice" (model.py) from "mechanical execution" (train.py)
    keeps the smoke harness honest AND speeds up codegen.

    design.md mirrors the agentic-pipeline pattern: it's a SOLID commitment
    doc the human reviews and the train.py runner uses as ground truth.
    Required sections:
      1. ## Architecture commitment       — concrete class + why over runner-up
      2. ## Hyperparameters (final)       — each value WITH per-line rationale
      3. ## Wall-clock budget             — estimate + overrun policy
      4. ## Success criteria              — hard target + oracle delta
      5. ## Risks & anti-patterns         — known traps for this arch+data
      6. ## Code structure                — what model.py exports
      7. ## Verification plan             — what the harness should check
    """
    model_config = ConfigDict(extra="forbid")
    design_md: str = Field(
        description=(
            "Markdown design doc (~400-700 words). MUST have all 7 sections "
            "listed in the system prompt. Concrete values everywhere — no "
            "ranges, no `tbd`, no `~`. Every hyperparameter line has a rationale."
        ),
    )
    model_py: str = Field(
        description=(
            "Contents of code/model.py. Defines exactly one function "
            "`build_model()` returning an unfitted sklearn estimator with the "
            "exact hyperparameter values committed to in design.md. "
            "No `if __name__ == '__main__'` — this file is imported only. "
            "Top-level code may import sklearn modules but MUST NOT do any I/O."
        ),
    )


def generate_design_and_code(
    llm: NemotronClient,
    spec: StrategySpec,
    profile: DatasetProfile,
    envelope: TrainingEnvelope,
    oracle: dict[str, Any],
    prep: PreparationReport | None,
    on_thinking=None,
    no_think: bool = True,
    previous_errors: list[str] | None = None,
) -> dict[str, str]:
    """ONE Nemotron call → {design_md, model.py, train.py}. ~30-60s in /no_think.

    The system prompt explicitly tells the model NOT to re-derive things the
    upstream agents already produced (architecture rationale, dataset
    description, preparation steps). It just commits to specifics + generates
    runnable sklearn code.

    `previous_errors`: if set, this is a retry — the listed errors from the
    last smoke harness run get appended to the user prompt so the model can
    fix them. Mirrors the agentic-pipeline `failures.md` feedback pattern.
    """
    arch = spec.candidate_architectures[0] if spec.candidate_architectures else None
    prepared_path = (
        prep.prepared_dataset_path if (prep and prep.prepared_dataset_path)
        else profile.dataset_path
    )

    system = (
        "You are the Trainer agent in the AutoForge pipeline. Upstream agents "
        "have ALREADY produced:\n"
        "  - Profiler: a DatasetProfile (modality, shape, target, task type)\n"
        "  - Researcher: a StrategySpec with ONE committed architecture (the "
        "    human just picked it at the candidate-pick HITL gate) plus "
        "    rationale + hyperparameter space + citations.\n"
        "  - Preparer: a PreparationReport with a prepared train/test split.\n\n"
        "DO NOT re-derive any of this. Your job is to COMMIT and SHIP a "
        "solid design.md + model.py.\n\n"
        "Produce TWO artifacts as one structured JSON object:\n\n"
        "================================================================\n"
        "## 1. design.md — solid commitment doc (~400-700 words)\n"
        "================================================================\n"
        "This is the contract the human approves at the design-gate HITL "
        "and what the train.py runner trusts as ground truth. Write it like "
        "an engineer who knows they'll be paged if it's wrong.\n\n"
        "REQUIRED sections (in this exact order, with these exact headings):\n\n"
        "### `## Architecture commitment`\n"
        "- The concrete sklearn class you're using (e.g. `MLPClassifier`).\n"
        "- One sentence: why this over the OTHER candidate(s) the Researcher "
        "  proposed (if any). Speak to dataset-specific traits.\n"
        "- One sentence: what aspect of the dataset makes this a good fit.\n\n"
        "### `## Hyperparameters (final)`\n"
        "Every hyperparameter on its own line, EXACT value, with a 1-line "
        "rationale. Format strictly:\n"
        "  - `param_name = value`  — Why this value.\n"
        "Example:\n"
        "  - `hidden_layer_sizes = (128, 64)` — Two-layer MLP: 128 captures "
        "    pixel-level features, 64 separates classes. Total ~110k params, "
        "    well under the envelope cap.\n"
        "  - `alpha = 1e-3` — Mild L2; dataset is small so we lean toward "
        "    regularization rather than wider layers.\n"
        "  - `max_iter = 30` — Enough for convergence on a tiny set without "
        "    blowing the 60s wall-clock.\n"
        "  - `random_state = 42` — Reproducibility.\n"
        "NO ranges. NO `tbd`. NO `~`. Pick ONE value for every HP your sklearn "
        "class supports that you intend to set.\n\n"
        "### `## Wall-clock budget`\n"
        "- Estimated train time on the prepared dataset (real seconds).\n"
        "- The cap from the envelope (must respect `max_train_minutes × 60`).\n"
        "- What we do if we hit the cap: reduce epochs? early-stop? abort?\n\n"
        "### `## Success criteria`\n"
        "- Hard target: `<metric>` ≥ `<threshold>` (from StrategySpec).\n"
        "- Oracle delta: must beat the sklearn LogReg baseline by ≥ 0.05.\n"
        "- State the oracle's measured test_accuracy so the delta is concrete.\n"
        "- Rollback trigger: one specific condition under which the run aborts "
        "  (e.g., `val_loss NaN after 3 epochs`, `accuracy ≤ oracle - 0.05`).\n\n"
        "### `## Risks & anti-patterns`\n"
        "- One concrete risk for THIS architecture on THIS dataset shape "
        "  (e.g., MLP on 28×28 grayscale → underfits without enough hidden "
        "  units; or trees on tiny sets → high variance).\n"
        "- One concrete anti-pattern we're avoiding (and why).\n"
        "- Overfitting risk given dataset size: one sentence.\n\n"
        "### `## Code structure`\n"
        "- `model.py` exports: `build_model() -> sklearn estimator`.\n"
        "- `train.py` is AutoForge-templated (do NOT generate). It will:\n"
        "  - Load `<data-dir>/train/` and `<data-dir>/test/` (image) OR "
        "    `train.csv` + `test.csv` (CSV).\n"
        "  - Call `model = build_model()` then `model.fit(X_train, y_train)`.\n"
        "  - Save `best.pkl` and emit `metrics.json` with `val_accuracy` + "
        "    `train_seconds`.\n"
        "- Required estimator surface: `.fit(X, y)` + `.predict(X)`.\n\n"
        "### `## Verification plan`\n"
        "- Smoke harness checks: `py_compile model.py`, `import build_model`, "
        "  `build_model()` instantiates without error.\n"
        "- After training: assert `val_accuracy >= oracle_accuracy + 0.05`.\n"
        "- Manual review: confirm the saved `best.pkl` loads with `joblib.load`.\n\n"
        "================================================================\n"
        "## 2. model.py — minimal, sklearn-only\n"
        "================================================================\n"
        "Defines EXACTLY one function `build_model()` returning an unfitted "
        "estimator with the EXACT hyperparameter values you committed to in "
        "the design's Hyperparameters section.\n\n"
        "### model.py shape (rigid)\n"
        "```python\n"
        "from sklearn.<your_module> import <YourClass>\n"
        "\n"
        "def build_model():\n"
        "    return <YourClass>(\n"
        "        <hp_1>=<value_1>,\n"
        "        <hp_2>=<value_2>,\n"
        "        random_state=42,\n"
        "    )\n"
        "```\n"
        "Allowed sklearn classes: MLPClassifier, LogisticRegression, "
        "RandomForestClassifier, GradientBoostingClassifier, SVC, "
        "KNeighborsClassifier, DecisionTreeClassifier.\n\n"
        "Imports allowed in model.py: anything from `sklearn.*`. Nothing else.\n"
        "No I/O. No top-level computation. No `if __name__ == '__main__'`.\n\n"
        "### Code quality (smoke harness will reject violations)\n"
        "- Every f-string must be properly terminated.\n"
        "- Every `(`, `[`, `{` must have a matching closer.\n"
        "- The code MUST `python -m py_compile` cleanly and `import` cleanly.\n"
        "- `build_model()` MUST be callable with zero args and return an estimator.\n"
        "- The hyperparameter values in model.py MUST match design.md exactly."
    )

    effective_target = max(
        spec.success_threshold, oracle["test_accuracy"] + 0.05,
    )
    user_lines = [
        f"## Inputs",
        f"- **Modality:** `{profile.modality.value}`",
        f"- **Task type:** `{profile.task_type.value}`",
        f"- **Target column (tabular only):** `{profile.target_column}`",
        f"- **Prepared data dir:** `{prepared_path}`",
        f"- **Samples:** {profile.n_rows:,} "
        + (f"(classes: {profile.n_classes})" if profile.n_classes else ""),
        f"- **Wall-clock cap:** {envelope.max_train_minutes * 60:.0f}s",
        "",
        f"## Targets",
        f"- **Hard target:** `{spec.success_metric}` ≥ {spec.success_threshold:.3f}",
        f"- **Oracle baseline (sklearn LogReg):** test_accuracy = "
        f"{oracle['test_accuracy']:.3f} (measured in "
        f"{oracle.get('wall_clock_s', 0.0):.1f}s on "
        f"n_train={oracle.get('n_train', '?')} / n_test={oracle.get('n_test', '?')}).",
        f"- **Effective target** (max of hard target and oracle+0.05): "
        f"≥ {effective_target:.3f}.",
        "",
        "## Researcher's committed architecture (already picked by human at HITL)",
    ]
    if arch is not None:
        user_lines.append(f"- **Name:** `{arch.name}`")
        user_lines.append(f"- **Family:** `{arch.family}`")
        user_lines.append(f"- **Library:** `{arch.library}`")
        user_lines.append(f"- **Rationale (from Researcher):** {arch.rationale}")
        user_lines.append(f"- **Hyperparameter space:** `{arch.hyperparameter_space}`")
        user_lines.append("")
        user_lines.append(
            "→ Pick ONE concrete value per hyperparameter. "
            "Use these as your starting point; you may add `random_state=42` "
            "and override any value the search space gave as a range."
        )
    user_lines.append("")
    if previous_errors:
        user_lines.append("## PREVIOUS ATTEMPT FAILED THE SMOKE HARNESS")
        user_lines.append("Fix these specific errors in this attempt:")
        for err in previous_errors:
            user_lines.append(f"- {err}")
        user_lines.append("")
        user_lines.append(
            "Carefully re-check every f-string, every bracket, every quote. "
            "Make sure the code passes `python -m py_compile`. The design.md "
            "structure stays the same — only the model.py needs fixing if the "
            "error was syntactic."
        )
        user_lines.append("")
    user_lines.append(
        "Produce the structured JSON now: design.md (all 7 sections, "
        "concrete values, rationales on every hyperparameter line) + model.py "
        "(rigid shape from system prompt, values matching design.md exactly). "
        "Do NOT generate train.py."
    )
    user = "\n".join(user_lines)

    result = llm.think_and_answer_structured(
        system=system,
        user=user,
        schema=_DesignAndCode,
        on_thinking=on_thinking,
        max_tokens=12000,
        temperature=0.2,
        no_think=no_think,
    )
    return {
        "design_md": result.design_md,
        "model.py": result.model_py,
    }


# Kept for back-compat in case anyone imports it directly; not called by the
# new TrainerAgent.
def generate_design_markdown(
    llm: NemotronClient,
    spec: StrategySpec,
    profile: DatasetProfile,
    envelope: TrainingEnvelope,
    oracle: dict[str, Any],
    on_thinking=None,
) -> str:
    """One Nemotron call → design.md markdown. Returns the text."""
    system = (
        "You are the Trainer agent. The Researcher proposed candidate "
        "architectures; the Profiler observed the dataset; the user supplied "
        "an objective. Your job RIGHT NOW is to commit to a specific design "
        "and document it as Markdown for human review.\n\n"
        "Output a single `design.md` document. Required sections:\n"
        "  ## Architecture            — concrete model class + layer sizes\n"
        "  ## Hyperparameters         — bullet list of the EXACT values\n"
        "  ## Training recipe         — optimizer, batch size, max epochs\n"
        "  ## Estimated wall-clock    — a real estimate in seconds\n"
        "  ## Success criteria        — hard threshold + oracle sanity check\n"
        "  ## Risks                   — what could go wrong\n\n"
        "Constraints:\n"
        "- Use sklearn ONLY (no PyTorch/TF). Acceptable classes: "
        "  MLPClassifier, LogisticRegression, RandomForestClassifier, SVC, "
        "  KNeighborsClassifier, GradientBoostingClassifier.\n"
        "- Param count MUST stay under `recommended_max_params` from the envelope.\n"
        "- Wall-clock estimate MUST be under `max_train_minutes * 60` seconds.\n"
        "- The model must plausibly beat the oracle baseline by ≥5 points.\n"
        "- Output the Markdown only — no JSON wrapper, no preamble, no code fence."
    )

    arch = spec.candidate_architectures[0] if spec.candidate_architectures else None
    user_lines = [
        f"## Objective\n{spec.objective}",
        f"\n## Dataset\n- modality: `{profile.modality.value}`",
        f"- task: `{profile.task_type.value}`",
        f"- samples: {profile.n_rows:,}",
    ]
    if profile.modality == Modality.TABULAR:
        user_lines.append(f"- columns: {profile.n_cols}")
        user_lines.append(f"- target: `{profile.target_column}`")
    else:
        user_lines.append(f"- classes: {profile.n_classes}")
        user_lines.append(f"- image_resolution: {profile.image_resolutions[:1]}")
        user_lines.append(f"- channels: {profile.image_channels}")
    if profile.class_balance:
        user_lines.append(f"- class balance: {profile.class_balance}")
    user_lines.extend([
        f"\n## Hardware envelope",
        f"- gpu: {envelope.gpu_name or 'CPU only'}",
        f"- max trials: {envelope.max_trials}",
        f"- max minutes: {envelope.max_train_minutes}",
        f"\n## Researcher's top candidate",
    ])
    if arch is not None:
        user_lines.append(
            f"- `{arch.name}` ({arch.family} / `{arch.library}`)"
        )
        user_lines.append(f"- rationale: {arch.rationale}")
        user_lines.append(f"- hyperparameter space: `{arch.hyperparameter_space}`")
    user_lines.extend([
        f"\n## Oracle baseline",
        f"- model: `{oracle['model']}`",
        f"- test_accuracy: {oracle['test_accuracy']:.3f}",
        f"- wall_clock_s: {oracle['wall_clock_s']:.1f}",
        f"\n## Success criteria",
        f"- hard: `{spec.success_metric}` ≥ {spec.success_threshold:.3f}",
        f"- oracle sanity: must beat baseline by ≥0.05",
        f"\nNow write `design.md`.",
    ])
    user_msg = "\n".join(user_lines)

    md = llm.think_and_answer(
        system=system,
        user=user_msg,
        on_thinking=on_thinking,
        max_tokens=4000,
        temperature=0.3,
    )
    # If the model wrapped in a fence, strip it
    md = md.strip()
    if md.startswith("```"):
        md = md.split("\n", 1)[1] if "\n" in md else md
        if md.endswith("```"):
            md = md.rsplit("```", 1)[0]
        md = md.strip()
    return md


# ===========================================================================
# Stage 3: Generate code
# ===========================================================================
class _GeneratedCode(BaseModel):
    """Structured output from the codegen LLM call."""
    model_config = ConfigDict(extra="forbid")
    model_py: str = Field(
        description="Contents of model.py. Must define `build_model()` "
        "returning a sklearn estimator."
    )
    train_py: str = Field(
        description="Contents of train.py. Must accept `--data-dir`, "
        "`--output-dir`, `--max-time-seconds`. Loads data, fits build_model(), "
        "saves model with joblib to `<output-dir>/best.pkl`, prints JSON metrics "
        "to stdout."
    )


def generate_code_files(
    llm: NemotronClient,
    design_md: str,
    profile: DatasetProfile,
    prep: PreparationReport | None,
    on_thinking=None,
) -> dict[str, str]:
    """One Nemotron call → dict of filename → code. Strict JSON output."""
    system = (
        "You generate sklearn Python code for the AutoForge Trainer.\n\n"
        "You will produce two files: `model.py` and `train.py`.\n\n"
        "## model.py contract\n"
        "Defines exactly one function: `build_model()`. Returns an unfitted "
        "sklearn estimator instance. Implements the architecture described "
        "in the design.md provided.\n\n"
        "## train.py contract\n"
        "Command-line program with argparse arguments:\n"
        "  --data-dir          path to prepared dataset (image: dir with train/+test/, csv: dir with train.csv+test.csv)\n"
        "  --output-dir        where to save best.pkl and metrics.json\n"
        "  --max-time-seconds  wall-clock budget (default 120). Self-terminate before exceeding.\n\n"
        "It MUST:\n"
        "  - Import build_model from model.py (same directory).\n"
        "  - Load training data from --data-dir using helpers defined IN train.py.\n"
        "  - For images: load PNGs as grayscale, flatten, normalize to [0,1].\n"
        "  - For tabular: read CSV with pandas, separate features from target.\n"
        "  - Call `model = build_model()` then `model.fit(X_train, y_train)`.\n"
        "  - Save the trained model to `<output-dir>/best.pkl` via `joblib.dump`.\n"
        "  - Compute validation accuracy on the test set.\n"
        "  - Print a single line of JSON to stdout: "
        "`{\"val_accuracy\": <float>, \"train_seconds\": <float>}`.\n"
        "  - Also write that JSON dict to `<output-dir>/metrics.json`.\n\n"
        "Imports allowed: argparse, json, time, pathlib, sys, numpy, sklearn.*, "
        "joblib, pandas, PIL.Image.\n\n"
        "Output a JSON object with keys `model_py` and `train_py`. The values "
        "are the Python source code as strings. No markdown fences inside the "
        "values — pure Python code only."
    )

    user = (
        "## design.md (the approved design you must implement)\n\n"
        f"{design_md}\n\n"
        f"## Modality: `{profile.modality.value}`\n"
        f"## Target column (CSV only): `{profile.target_column}`\n\n"
        f"Generate the two Python files now."
    )

    result: _GeneratedCode = llm.think_and_answer_structured(
        system=system,
        user=user,
        schema=_GeneratedCode,
        on_thinking=on_thinking,
        max_tokens=12000,
        temperature=0.2,
    )
    return {
        "model.py": result.model_py,
        "train.py": result.train_py,
    }


# ===========================================================================
# Stage 4: Smoke harness
# ===========================================================================
def run_smoke_harness(code_dir: Path) -> dict[str, Any]:
    """Verify generated code is at least syntactically + structurally sane.

    Returns a dict with `overall_passed: bool` and per-check details. ERROR-
    prefixed lines for grep. Mirrors agentic-pipeline's verify_report.json.
    """
    checks: list[dict[str, Any]] = []

    def add(name: str, passed: bool, detail: str = "") -> None:
        checks.append({"name": name, "passed": passed, "detail": detail})

    # Check 1: py_compile each .py
    for filename in ("model.py", "train.py"):
        path = code_dir / filename
        if not path.exists():
            add(f"file_exists_{filename}", False, f"ERROR: {filename} missing")
            continue
        add(f"file_exists_{filename}", True)
        compile_result = subprocess.run(
            [sys.executable, "-m", "py_compile", str(path)],
            capture_output=True, text=True, timeout=30,
        )
        if compile_result.returncode != 0:
            add(f"syntax_{filename}", False,
                f"ERROR: {compile_result.stderr.strip()[:300]}")
        else:
            add(f"syntax_{filename}", True)

    # If syntax failed, don't bother trying to import
    syntax_ok = all(c["passed"] for c in checks if c["name"].startswith("syntax_"))
    if not syntax_ok:
        return {
            "overall_passed": False,
            "checks": checks,
            "reason": "ERROR: syntax check(s) failed; skipping import + build",
        }

    # Check 2: import + has build_model
    import_test = (
        f"import sys; sys.path.insert(0, r'{code_dir}'); "
        "from model import build_model; "
        "m = build_model(); "
        "print('IMPORT_OK type=' + type(m).__name__)"
    )
    import_result = subprocess.run(
        [sys.executable, "-c", import_test],
        capture_output=True, text=True, timeout=60,
    )
    if import_result.returncode != 0 or "IMPORT_OK" not in import_result.stdout:
        err = import_result.stderr.strip()[:500] or import_result.stdout.strip()[:500]
        add("import_build_model", False, f"ERROR: {err}")
    else:
        add("import_build_model", True, import_result.stdout.strip())

    overall = all(c["passed"] for c in checks)
    return {
        "overall_passed": overall,
        "checks": checks,
        "reason": "" if overall else "ERROR: one or more checks failed",
    }


# ===========================================================================
# Stage 5: Subprocess training
# ===========================================================================
def run_training_subprocess(
    code_dir: Path,
    prepared_dir: Path,
    output_dir: Path,
    log_dir: Path,
    max_time_seconds: int,
) -> dict[str, Any]:
    """Run `python code/train.py --data-dir ... --output-dir ... --max-time-seconds N`.

    Captures stdout/stderr to log files. Returns dict with metrics + status.
    Soft-success: if process times out but `best.pkl` exists, treat as success.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    log_dir.mkdir(parents=True, exist_ok=True)
    stdout_log = log_dir / "train_stdout.log"
    stderr_log = log_dir / "train_stderr.log"

    cmd = [
        sys.executable,
        str(code_dir / "train.py"),
        "--data-dir", str(prepared_dir),
        "--output-dir", str(output_dir),
        "--max-time-seconds", str(max_time_seconds),
    ]

    t0 = time.time()
    timed_out = False
    return_code: int | None = None
    try:
        with open(stdout_log, "w", encoding="utf-8") as out_f, \
             open(stderr_log, "w", encoding="utf-8") as err_f:
            result = subprocess.run(
                cmd,
                stdout=out_f,
                stderr=err_f,
                timeout=max_time_seconds + 30,  # small grace
                cwd=str(code_dir),
            )
            return_code = result.returncode
    except subprocess.TimeoutExpired:
        timed_out = True
    duration = time.time() - t0

    best_pkl = output_dir / "best.pkl"
    metrics_json = output_dir / "metrics.json"

    metrics: dict[str, Any] = {}
    if metrics_json.exists():
        try:
            metrics = json.loads(metrics_json.read_text())
        except Exception:  # noqa: BLE001
            metrics = {"parse_error": "metrics.json present but unparseable"}

    # Last 50 lines of each log for the agent to see
    def _tail(p: Path, n: int = 50) -> str:
        if not p.exists():
            return ""
        try:
            lines = p.read_text(encoding="utf-8").splitlines()
            return "\n".join(lines[-n:])
        except Exception:  # noqa: BLE001
            return ""

    soft_success = best_pkl.exists()
    success = (return_code == 0 and not timed_out) or soft_success
    return {
        "success": success,
        "return_code": return_code,
        "timed_out": timed_out,
        "duration_s": duration,
        "best_pkl": str(best_pkl) if best_pkl.exists() else None,
        "metrics": metrics,
        "stdout_tail": _tail(stdout_log),
        "stderr_tail": _tail(stderr_log),
    }
